# Generated by Django 5.2 on 2025-04-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='is_natural_language',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presentation',
            name='use_template',
            field=models.BooleanField(default=False),
        ),
    ]
