# Generated by Django 5.2 on 2025-04-04 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation_app', '0002_presentation_is_natural_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='is_natural_language',
        ),
        migrations.AddField(
            model_name='presentation',
            name='content_type',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('natural_language', '自然言語')], default='markdown', max_length=20, verbose_name='コンテンツタイプ'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='font_size',
            field=models.CharField(choices=[('large', '大きい'), ('medium', '中くらい'), ('small', '小さい'), ('auto', '自動判定')], default='auto', max_length=10, verbose_name='フォントサイズ'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='max_chars_per_slide',
            field=models.IntegerField(default=0, verbose_name='1スライドあたりの最大文字数'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='theme',
            field=models.CharField(default='default', max_length=50, verbose_name='テーマ'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='use_template',
            field=models.BooleanField(default=False, verbose_name='テンプレート使用'),
        ),
    ]
