# Generated by Django 5.2 on 2025-04-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation_app', '0004_presentation_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='use_template',
        ),
        migrations.AlterField(
            model_name='presentation',
            name='content_type',
            field=models.CharField(choices=[('markdown', 'Markdown')], default='markdown', max_length=20, verbose_name='コンテンツタイプ'),
        ),
    ]
